### ISSUE TITLE
Can not run `build` script

### ISSUE THREAD

**Issue by octopitus** [fed135/Kalm#28]
Hi there,

I tried to run `npm run build` but seem like it doesn't work. Any ideas?

`npm-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/y/.nvm/versions/node/v6.0.0/bin/node',
1 verbose cli   '/home/y/.nvm/versions/node/v6.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.8.6
3 info using node@v6.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle kalm@1.2.0~prebuild: kalm@1.2.0
6 silly lifecycle kalm@1.2.0~prebuild: no script for prebuild, continuing
7 info lifecycle kalm@1.2.0~build: kalm@1.2.0
8 verbose lifecycle kalm@1.2.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle kalm@1.2.0~build: PATH: /home/y/.nvm/versions/node/v6.0.0/lib/node_modules/npm/bin/node-gyp-bin:/home/y/projects/Kalm/node_modules/.bin:/home/y/.nvm/versions/node/v6.0.0/bin:/home/y/.nvm/versions/node/v6.0.0/bin:/home/y/.gvm/pkgsets/go1.4.2/global/bin:/home/y/.gvm/gos/go1.4.2/bin:/home/y/.gvm/pkgsets/go1.4.2/global/overlay/bin:/home/y/.gvm/bin:/home/y/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/share/android-sdk/tools:/usr/share/android-sdk/platform-tools
10 verbose lifecycle kalm@1.2.0~build: CWD: /home/y/projects/Kalm
11 silly lifecycle kalm@1.2.0~build: Args: [ '-c',
11 silly lifecycle   'webpack -p -d -j --define process.env.NODE_ENV=\'"browser"\' --config ./webpack.config && babel --no-comments --compact "true" --minified --plugins transform-es2015-parameters -o ./bin/kalm.min.js < ./bin/kalm.js' ]
12 silly lifecycle kalm@1.2.0~build: Returned: code: 2  signal: null
13 info lifecycle kalm@1.2.0~build: Failed to exec build script
14 verbose stack Error: kalm@1.2.0 build: `webpack -p -d -j --define process.env.NODE_ENV='"browser"' --config ./webpack.config && babel --no-comments --compact "true" --minified --plugins transform-es2015-parameters -o ./bin/kalm.min.js < ./bin/kalm.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/home/y/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/y/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid kalm@1.2.0
16 verbose cwd /home/y/projects/Kalm
17 error Linux 3.16.0-57-generic
18 error argv "/home/y/.nvm/versions/node/v6.0.0/bin/node" "/home/y/.nvm/versions/node/v6.0.0/bin/npm" "run" "build"
19 error node v6.0.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error kalm@1.2.0 build: `webpack -p -d -j --define process.env.NODE_ENV='"browser"' --config ./webpack.config && babel --no-comments --compact "true" --minified --plugins transform-es2015-parameters -o ./bin/kalm.min.js < ./bin/kalm.js`
22 error Exit status 2
23 error Failed at the kalm@1.2.0 build script 'webpack -p -d -j --define process.env.NODE_ENV='"browser"' --config ./webpack.config && babel --no-comments --compact "true" --minified --plugins transform-es2015-parameters -o ./bin/kalm.min.js < ./bin/kalm.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the kalm package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack -p -d -j --define process.env.NODE_ENV='"browser"' --config ./webpack.config && babel --no-comments --compact "true" --minified --plugins transform-es2015-parameters -o ./bin/kalm.min.js < ./bin/kalm.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs kalm
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls kalm
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

When omitted `-d` and ` -j` of webpack, I got this output on terminal:
```
ERROR in ./src/adapters/ipc.js
Module not found: Error: Cannot resolve module 'net' in /home/y/projects/Kalm/src/adapters
 @ ./src/adapters/ipc.js 10:12-26

ERROR in ./src/adapters/tcp.js
Module not found: Error: Cannot resolve module 'net' in /home/y/projects/Kalm/src/adapters
 @ ./src/adapters/tcp.js 10:12-26

ERROR in ./src/adapters/ipc.js
Module not found: Error: Cannot resolve module 'fs' in /home/y/projects/Kalm/src/adapters
 @ ./src/adapters/ipc.js 11:11-24

ERROR in ./src/adapters/udp.js
Module not found: Error: Cannot resolve module 'dgram' in /home/y/projects/Kalm/src/adapters
 @ ./src/adapters/udp.js 10:14-30

ERROR in kalm.min.js from UglifyJs
SyntaxError: Unexpected token: name (Adapter) [./src/adapters/common.js:13,0]
```

Seems like webpack's config missed `target: 'node'`.

Fantastic work btw!

**Comment by fed135** [comment]
Hey thanks, I'll take a look at this. 

Make sure you have a `bin` folder in the project (should probably add a .gitempty or mkdir) - this is where the built file is saved.

As for the `net`, `fs` and `dgram` modules, they are not available/polyfillable for browser use. This is why I use the `NODE_ENV=browser` flag. When in browser mode `tcp`, `udp` and `ipc` are thus unavailable.

**Comment by octopitus** [comment]
It said that `cannot open ./bin/kalm.js: No such file`. Maybe the output filename in webpack should be `kalm.js`?

**Comment by fed135** [comment]
Good catch! I pushed a fix on `master`. I'll let you confirm and close this issue.
Thanks!

**Comment by octopitus** [comment]
It's good right now.

Btw, should we use Babel & webpack to make Kalm campatible with NODE < 6.0?
I will make a pull request.
